package organization

type countryDefaults struct {
	Currency string
	Timezone string
}

var countryDefaultsMap = map[string]countryDefaults{
	"AD": {Currency: "EUR", Timezone: "Europe/Andorra"},
	"AE": {Currency: "AED", Timezone: "Asia/Dubai"},
	"AF": {Currency: "AFN", Timezone: "Asia/Kabul"},
	"AG": {Currency: "XCD", Timezone: "America/Antigua"},
	"AL": {Currency: "ALL", Timezone: "Europe/Tirane"},
	"AM": {Currency: "AMD", Timezone: "Asia/Yerevan"},
	"AO": {Currency: "AOA", Timezone: "Africa/Luanda"},
	"AR": {Currency: "ARS", Timezone: "America/Argentina/Buenos_Aires"},
	"AT": {Currency: "EUR", Timezone: "Europe/Vienna"},
	"AU": {Currency: "AUD", Timezone: "Australia/Sydney"},
	"AZ": {Currency: "AZN", Timezone: "Asia/Baku"},
	"BA": {Currency: "BAM", Timezone: "Europe/Sarajevo"},
	"BB": {Currency: "BBD", Timezone: "America/Barbados"},
	"BD": {Currency: "BDT", Timezone: "Asia/Dhaka"},
	"BE": {Currency: "EUR", Timezone: "Europe/Brussels"},
	"BF": {Currency: "XOF", Timezone: "Africa/Ouagadougou"},
	"BG": {Currency: "BGN", Timezone: "Europe/Sofia"},
	"BH": {Currency: "BHD", Timezone: "Asia/Bahrain"},
	"BI": {Currency: "BIF", Timezone: "Africa/Bujumbura"},
	"BJ": {Currency: "XOF", Timezone: "Africa/Porto-Novo"},
	"BN": {Currency: "BND", Timezone: "Asia/Brunei"},
	"BO": {Currency: "BOB", Timezone: "America/La_Paz"},
	"BR": {Currency: "BRL", Timezone: "America/Sao_Paulo"},
	"BS": {Currency: "BSD", Timezone: "America/Nassau"},
	"BT": {Currency: "BTN", Timezone: "Asia/Thimphu"},
	"BW": {Currency: "BWP", Timezone: "Africa/Gaborone"},
	"BY": {Currency: "BYN", Timezone: "Europe/Minsk"},
	"BZ": {Currency: "BZD", Timezone: "America/Belize"},
	"CA": {Currency: "CAD", Timezone: "America/Toronto"},
	"CD": {Currency: "CDF", Timezone: "Africa/Kinshasa"},
	"CF": {Currency: "XAF", Timezone: "Africa/Bangui"},
	"CG": {Currency: "XAF", Timezone: "Africa/Brazzaville"},
	"CH": {Currency: "CHF", Timezone: "Europe/Zurich"},
	"CI": {Currency: "XOF", Timezone: "Africa/Abidjan"},
	"CL": {Currency: "CLP", Timezone: "America/Santiago"},
	"CM": {Currency: "XAF", Timezone: "Africa/Douala"},
	"CN": {Currency: "CNY", Timezone: "Asia/Shanghai"},
	"CO": {Currency: "COP", Timezone: "America/Bogota"},
	"CR": {Currency: "CRC", Timezone: "America/Costa_Rica"},
	"CU": {Currency: "CUP", Timezone: "America/Havana"},
	"CV": {Currency: "CVE", Timezone: "Atlantic/Cape_Verde"},
	"CZ": {Currency: "CZK", Timezone: "Europe/Prague"},
	"DE": {Currency: "EUR", Timezone: "Europe/Berlin"},
	"DJ": {Currency: "DJF", Timezone: "Africa/Djibouti"},
	"DK": {Currency: "DKK", Timezone: "Europe/Copenhagen"},
	"DM": {Currency: "XCD", Timezone: "America/Dominica"},
	"DO": {Currency: "DOP", Timezone: "America/Santo_Domingo"},
	"DZ": {Currency: "DZD", Timezone: "Africa/Algiers"},
	"EC": {Currency: "USD", Timezone: "America/Guayaquil"},
	"EE": {Currency: "EUR", Timezone: "Europe/Tallinn"},
	"EG": {Currency: "EGP", Timezone: "Africa/Cairo"},
	"ER": {Currency: "ERN", Timezone: "Africa/Asmara"},
	"ES": {Currency: "EUR", Timezone: "Europe/Madrid"},
	"ET": {Currency: "ETB", Timezone: "Africa/Addis_Ababa"},
	"FI": {Currency: "EUR", Timezone: "Europe/Helsinki"},
	"FJ": {Currency: "FJD", Timezone: "Pacific/Fiji"},
	"FR": {Currency: "EUR", Timezone: "Europe/Paris"},
	"GA": {Currency: "XAF", Timezone: "Africa/Libreville"},
	"GB": {Currency: "GBP", Timezone: "Europe/London"},
	"GD": {Currency: "XCD", Timezone: "America/Grenada"},
	"GE": {Currency: "GEL", Timezone: "Asia/Tbilisi"},
	"GH": {Currency: "GHS", Timezone: "Africa/Accra"},
	"GM": {Currency: "GMD", Timezone: "Africa/Banjul"},
	"GN": {Currency: "GNF", Timezone: "Africa/Conakry"},
	"GQ": {Currency: "XAF", Timezone: "Africa/Malabo"},
	"GR": {Currency: "EUR", Timezone: "Europe/Athens"},
	"GT": {Currency: "GTQ", Timezone: "America/Guatemala"},
	"GW": {Currency: "XOF", Timezone: "Africa/Bissau"},
	"GY": {Currency: "GYD", Timezone: "America/Guyana"},
	"HN": {Currency: "HNL", Timezone: "America/Tegucigalpa"},
	"HR": {Currency: "EUR", Timezone: "Europe/Zagreb"},
	"HT": {Currency: "HTG", Timezone: "America/Port-au-Prince"},
	"HU": {Currency: "HUF", Timezone: "Europe/Budapest"},
	"ID": {Currency: "IDR", Timezone: "Asia/Jakarta"},
	"IE": {Currency: "EUR", Timezone: "Europe/Dublin"},
	"IL": {Currency: "ILS", Timezone: "Asia/Jerusalem"},
	"IN": {Currency: "INR", Timezone: "Asia/Kolkata"},
	"IQ": {Currency: "IQD", Timezone: "Asia/Baghdad"},
	"IR": {Currency: "IRR", Timezone: "Asia/Tehran"},
	"IS": {Currency: "ISK", Timezone: "Atlantic/Reykjavik"},
	"IT": {Currency: "EUR", Timezone: "Europe/Rome"},
	"JM": {Currency: "JMD", Timezone: "America/Jamaica"},
	"JO": {Currency: "JOD", Timezone: "Asia/Amman"},
	"JP": {Currency: "JPY", Timezone: "Asia/Tokyo"},
	"KE": {Currency: "KES", Timezone: "Africa/Nairobi"},
	"KG": {Currency: "KGS", Timezone: "Asia/Bishkek"},
	"KH": {Currency: "KHR", Timezone: "Asia/Phnom_Penh"},
	"KI": {Currency: "AUD", Timezone: "Pacific/Tarawa"},
	"KM": {Currency: "KMF", Timezone: "Indian/Comoro"},
	"KN": {Currency: "XCD", Timezone: "America/St_Kitts"},
	"KP": {Currency: "KPW", Timezone: "Asia/Pyongyang"},
	"KR": {Currency: "KRW", Timezone: "Asia/Seoul"},
	"KW": {Currency: "KWD", Timezone: "Asia/Kuwait"},
	"KZ": {Currency: "KZT", Timezone: "Asia/Almaty"},
	"LA": {Currency: "LAK", Timezone: "Asia/Vientiane"},
	"LB": {Currency: "LBP", Timezone: "Asia/Beirut"},
	"LC": {Currency: "XCD", Timezone: "America/St_Lucia"},
	"LI": {Currency: "CHF", Timezone: "Europe/Vaduz"},
	"LK": {Currency: "LKR", Timezone: "Asia/Colombo"},
	"LR": {Currency: "LRD", Timezone: "Africa/Monrovia"},
	"LS": {Currency: "LSL", Timezone: "Africa/Maseru"},
	"LT": {Currency: "EUR", Timezone: "Europe/Vilnius"},
	"LU": {Currency: "EUR", Timezone: "Europe/Luxembourg"},
	"LV": {Currency: "EUR", Timezone: "Europe/Riga"},
	"LY": {Currency: "LYD", Timezone: "Africa/Tripoli"},
	"MA": {Currency: "MAD", Timezone: "Africa/Casablanca"},
	"MC": {Currency: "EUR", Timezone: "Europe/Monaco"},
	"MD": {Currency: "MDL", Timezone: "Europe/Chisinau"},
	"ME": {Currency: "EUR", Timezone: "Europe/Podgorica"},
	"MG": {Currency: "MGA", Timezone: "Indian/Antananarivo"},
	"MK": {Currency: "MKD", Timezone: "Europe/Skopje"},
	"ML": {Currency: "XOF", Timezone: "Africa/Bamako"},
	"MM": {Currency: "MMK", Timezone: "Asia/Yangon"},
	"MN": {Currency: "MNT", Timezone: "Asia/Ulaanbaatar"},
	"MR": {Currency: "MRU", Timezone: "Africa/Nouakchott"},
	"MT": {Currency: "EUR", Timezone: "Europe/Malta"},
	"MU": {Currency: "MUR", Timezone: "Indian/Mauritius"},
	"MV": {Currency: "MVR", Timezone: "Indian/Maldives"},
	"MW": {Currency: "MWK", Timezone: "Africa/Blantyre"},
	"MX": {Currency: "MXN", Timezone: "America/Mexico_City"},
	"MY": {Currency: "MYR", Timezone: "Asia/Kuala_Lumpur"},
	"MZ": {Currency: "MZN", Timezone: "Africa/Maputo"},
	"NA": {Currency: "NAD", Timezone: "Africa/Windhoek"},
	"NE": {Currency: "XOF", Timezone: "Africa/Niamey"},
	"NG": {Currency: "NGN", Timezone: "Africa/Lagos"},
	"NI": {Currency: "NIO", Timezone: "America/Managua"},
	"NL": {Currency: "EUR", Timezone: "Europe/Amsterdam"},
	"NO": {Currency: "NOK", Timezone: "Europe/Oslo"},
	"NP": {Currency: "NPR", Timezone: "Asia/Kathmandu"},
	"NZ": {Currency: "NZD", Timezone: "Pacific/Auckland"},
	"OM": {Currency: "OMR", Timezone: "Asia/Muscat"},
	"PA": {Currency: "PAB", Timezone: "America/Panama"},
	"PE": {Currency: "PEN", Timezone: "America/Lima"},
	"PG": {Currency: "PGK", Timezone: "Pacific/Port_Moresby"},
	"PH": {Currency: "PHP", Timezone: "Asia/Manila"},
	"PK": {Currency: "PKR", Timezone: "Asia/Karachi"},
	"PL": {Currency: "PLN", Timezone: "Europe/Warsaw"},
	"PT": {Currency: "EUR", Timezone: "Europe/Lisbon"},
	"PY": {Currency: "PYG", Timezone: "America/Asuncion"},
	"QA": {Currency: "QAR", Timezone: "Asia/Qatar"},
	"RO": {Currency: "RON", Timezone: "Europe/Bucharest"},
	"RS": {Currency: "RSD", Timezone: "Europe/Belgrade"},
	"RU": {Currency: "RUB", Timezone: "Europe/Moscow"},
	"RW": {Currency: "RWF", Timezone: "Africa/Kigali"},
	"SA": {Currency: "SAR", Timezone: "Asia/Riyadh"},
	"SB": {Currency: "SBD", Timezone: "Pacific/Guadalcanal"},
	"SC": {Currency: "SCR", Timezone: "Indian/Mahe"},
	"SD": {Currency: "SDG", Timezone: "Africa/Khartoum"},
	"SE": {Currency: "SEK", Timezone: "Europe/Stockholm"},
	"SG": {Currency: "SGD", Timezone: "Asia/Singapore"},
	"SI": {Currency: "EUR", Timezone: "Europe/Ljubljana"},
	"SK": {Currency: "EUR", Timezone: "Europe/Bratislava"},
	"SL": {Currency: "SLL", Timezone: "Africa/Freetown"},
	"SM": {Currency: "EUR", Timezone: "Europe/San_Marino"},
	"SN": {Currency: "XOF", Timezone: "Africa/Dakar"},
	"SO": {Currency: "SOS", Timezone: "Africa/Mogadishu"},
	"SR": {Currency: "SRD", Timezone: "America/Paramaribo"},
	"SS": {Currency: "SSP", Timezone: "Africa/Juba"},
	"SV": {Currency: "USD", Timezone: "America/El_Salvador"},
	"SY": {Currency: "SYP", Timezone: "Asia/Damascus"},
	"SZ": {Currency: "SZL", Timezone: "Africa/Mbabane"},
	"TD": {Currency: "XAF", Timezone: "Africa/Ndjamena"},
	"TG": {Currency: "XOF", Timezone: "Africa/Lome"},
	"TH": {Currency: "THB", Timezone: "Asia/Bangkok"},
	"TJ": {Currency: "TJS", Timezone: "Asia/Dushanbe"},
	"TM": {Currency: "TMT", Timezone: "Asia/Ashgabat"},
	"TN": {Currency: "TND", Timezone: "Africa/Tunis"},
	"TO": {Currency: "TOP", Timezone: "Pacific/Tongatapu"},
	"TR": {Currency: "TRY", Timezone: "Europe/Istanbul"},
	"TT": {Currency: "TTD", Timezone: "America/Port_of_Spain"},
	"TW": {Currency: "TWD", Timezone: "Asia/Taipei"},
	"TZ": {Currency: "TZS", Timezone: "Africa/Dar_es_Salaam"},
	"UA": {Currency: "UAH", Timezone: "Europe/Kiev"},
	"UG": {Currency: "UGX", Timezone: "Africa/Kampala"},
	"US": {Currency: "USD", Timezone: "America/New_York"},
	"UY": {Currency: "UYU", Timezone: "America/Montevideo"},
	"UZ": {Currency: "UZS", Timezone: "Asia/Tashkent"},
	"VE": {Currency: "VES", Timezone: "America/Caracas"},
	"VN": {Currency: "VND", Timezone: "Asia/Ho_Chi_Minh"},
	"VU": {Currency: "VUV", Timezone: "Pacific/Efate"},
	"WS": {Currency: "WST", Timezone: "Pacific/Apia"},
	"YE": {Currency: "YER", Timezone: "Asia/Aden"},
	"ZA": {Currency: "ZAR", Timezone: "Africa/Johannesburg"},
	"ZM": {Currency: "ZMW", Timezone: "Africa/Lusaka"},
	"ZW": {Currency: "ZWL", Timezone: "Africa/Harare"},
}

func lookupCountryDefaults(code string) (*countryDefaults, bool) {
	if len(code) != 2 {
		return nil, false
	}
	upper := []byte(code)
	for i, b := range upper {
		if b >= 'a' && b <= 'z' {
			upper[i] = b - 32
		}
	}
	d, ok := countryDefaultsMap[string(upper)]
	return &d, ok
}
