package handler

import (
	"strconv"

	"github.com/gofiber/fiber/v3"
	"github.com/jalusw/swantara/apps/service/internal/httpx"
)

type InboundCostAdjustmentResponse struct {
	ID              uint64  `json:"id"`
	StockMovementID uint64  `json:"stock_movement_id"`
	ItemID          uint64  `json:"item_id"`
	AdditionalCost  float64 `json:"additional_cost"`
	CostLayerID     uint64  `json:"cost_layer_id"`
}

type ListInboundCostAdjustmentsResponseEnvelope struct {
	httpx.EnvelopeBase
	Data ListInboundCostAdjustmentsResponse `json:"data"`
}

type ListInboundCostAdjustmentsResponse struct {
	Adjustments []InboundCostAdjustmentResponse `json:"adjustments"`
}

// @Summary List inbound cost adjustments
// @Description Lists the cost layer adjustments generated by a posted inbound cost.
// @Tags Landed Costs
// @Accept json
// @Produce json
// @Param id path integer true "Inbound cost ID"
// @Success 200 {object} ListInboundCostAdjustmentsResponseEnvelope "Inbound cost adjustments retrieved successfully."
// @Failure 401 {object} httpx.ErrorResponse "Unauthorized"
// @Failure 404 {object} httpx.ErrorResponse "Inbound cost not found"
// @Failure 500 {object} httpx.ErrorResponse "Internal server error"
// @Security BearerAuth
// @Param organization_id path integer true "Organization ID"
// @Router /organizations/{organization_id}/landed-costs/{id}/adjustments [get]
func (h InboundCostHandler) ListAdjustments(c fiber.Ctx) error {
	organizationID := httpx.TenantOrganizationID(c, nil)
	if organizationID == nil {
		return httpx.CreateUnprocessableEntityErrorResponse(c, "Organization is required.", nil)
	}

	costID, err := strconv.ParseUint(c.Params("id"), 10, 64)
	if err != nil {
		return httpx.CreateUnprocessableEntityErrorResponse(c, "Invalid inbound cost id provided.", nil)
	}

	adjustments, err := h.svc.ListAdjustments(c, *organizationID, costID)
	if err != nil {
		return writeInboundCostError(c, err)
	}

	items := make([]InboundCostAdjustmentResponse, len(adjustments))
	for i, adjustment := range adjustments {
		items[i] = InboundCostAdjustmentResponse{
			ID:              adjustment.ID,
			StockMovementID: adjustment.StockMovementID,
			ItemID:          adjustment.ItemID,
			AdditionalCost:  adjustment.AdditionalCost,
			CostLayerID:     adjustment.CostLayerID,
		}
	}

	return httpx.CreateSuccessResponse(c, "Inbound cost adjustments retrieved successfully.", ListInboundCostAdjustmentsResponse{
		Adjustments: items,
	})
}
