version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - misspell
    - revive

  settings:
    govet:
      disable:
        - inline
    gocritic:
      disabled-checks:
        - ifElseChain
    revive:
      rules:
        - name: exported
          disabled: true

formatters:
  enable:
    - gofmt
    - goimports

issues:
  exclude-dirs:
    - node_modules
    - bin
  exclude-files:
    - ".*_test\\.go$"
