package inventory

import "errors"

var (
	ErrWarehouseNotFound         = errors.New("warehouse not found")
	ErrWarehouseNameRequired     = errors.New("warehouse name is required")
	ErrWarehouseCodeTaken        = errors.New("warehouse code already exists")
	ErrLocationNotFound          = errors.New("stock location not found")
	ErrLocationNameRequired      = errors.New("stock location name is required")
	ErrLocationParent            = errors.New("parent stock location not found")
	ErrWarehouseMismatch         = errors.New("stock location organization does not match its warehouse")
	ErrInvalidLocationType       = errors.New("invalid location usage type")
	ErrMovementNotFound          = errors.New("stock movement not found")
	ErrMovementItem              = errors.New("stock movement item is required")
	ErrMovementQty               = errors.New("stock movement quantity must be greater than zero")
	ErrMovementState             = errors.New("stock movement cannot be completed in its current state")
	ErrInsufficientStock         = errors.New("insufficient stock for this operation")
	ErrVariantNotFound           = errors.New("item variant not found")
	ErrBatchRequired             = errors.New("this item requires batch/serial tracking")
	ErrBatchNotFound             = errors.New("stock batch not found")
	ErrBatchNameTaken            = errors.New("batch name already exists for this item")
	ErrBalanceNotFound           = errors.New("stock balance not found")
	ErrHoldOverflow              = errors.New("hold exceeds available-to-promise")
	ErrHoldConflict              = errors.New("stock hold could not be persisted")
	ErrHoldNotFound              = errors.New("stock hold not found")
	ErrRuleNotFound              = errors.New("reorder rule not found")
	ErrInvalidRuleQty            = errors.New("reorder rule quantities are invalid")
	ErrStockCountNotFound        = errors.New("stock count not found")
	ErrStockCountState           = errors.New("stock count cannot be posted in its current state")
	ErrStockCountNoLines         = errors.New("stock count has no lines")
	ErrWarehouseTransferNotFound = errors.New("warehouse transfer not found")
	ErrWarehouseTransferState    = errors.New("warehouse transfer cannot transition in its current state")
	ErrSameWarehouse             = errors.New("source and destination warehouses must differ")
	ErrTransitNotFound           = errors.New("no transit location found for this organization")
	ErrItemNotFound              = errors.New("item not found")
	ErrNoValuation               = errors.New("item has no cost layers")
	ErrNotReceipt                = errors.New("movement is not an incoming receipt")
	ErrNotShipment               = errors.New("movement is not an outgoing shipment")
	ErrNotScrap                  = errors.New("movement is not routed to a scrap location")
	ErrNotReturn                 = errors.New("movement does not originate from a customer location")
	ErrNotSupplierReturn         = errors.New("movement is not routed back to a supplier location")
	ErrNotConsumption            = errors.New("movement is not routed to a production location")
	ErrNotProduction             = errors.New("movement does not originate from a production location")
	ErrNegativeCost              = errors.New("unit cost cannot be negative")
	ErrStandardCostMissing       = errors.New("standard-cost item requires a standard cost")
	ErrOrganizationMissing       = errors.New("organization is required for posting")
	ErrValuationAccount          = errors.New("item category has no stock cost account")
	ErrInputAccount              = errors.New("item category has no stock input account")
	ErrCogsAccount               = errors.New("item category has no COGS account")
	ErrScrapAccount              = errors.New("scrap expense account is required")
	ErrWIPAccount                = errors.New("work in progress account is required")
	ErrTransitAccount            = errors.New("goods in transit account is required")
	ErrGainLossAccount           = errors.New("inventory gain/loss account is required")
	ErrBatchTrackingDisabled     = errors.New("item does not use batch/serial tracking")
	ErrLocationRequired          = errors.New("location is required")
	ErrStockCountLine            = errors.New("stock count line references an item without stock")
	ErrInboundCostNotFound       = errors.New("inbound cost not found")
	ErrInboundCostState          = errors.New("inbound cost cannot be posted in its current state")
	ErrInboundCostNoLines        = errors.New("inbound cost has no lines")
	ErrInboundCostNoShipments    = errors.New("inbound cost has no target shipments")
	ErrInboundCostNoMovements    = errors.New("inbound cost line has no matching receipt movements")
	ErrInboundCostNoAccount      = errors.New("inbound cost line has no clearing account")
	ErrInboundCostNoJournal      = errors.New("inbound cost journal is not configured")
	ErrInboundCostSplit          = errors.New("invalid landed cost split method")
	ErrInboundCostValue          = errors.New("inbound cost value split requires received movements with unit cost")
)
