package procurement

import "errors"

var (
	ErrRequisitionNotFound       = errors.New("purchase requisition not found")
	ErrRequestState              = errors.New("purchase requisition is not in the required state")
	ErrRequisitionNoLines        = errors.New("purchase requisition must have at least one line")
	ErrRequisitionLineQty        = errors.New("purchase requisition line quantity must be positive")
	ErrRequisitionRequester      = errors.New("purchase requisition requester does not exist")
	ErrRequisitionNotConvertible = errors.New("purchase requisition must be approved before conversion")

	ErrPurchaseOrderNotFound             = errors.New("purchase order not found")
	ErrPurchaseOrderState                = errors.New("purchase order is not in the required state")
	ErrPurchaseOrderNoLines              = errors.New("purchase order must have at least one line")
	ErrPurchaseOrderLineNotFound         = errors.New("purchase order line not found")
	ErrPurchaseOrderLineQty              = errors.New("purchase order line quantity must be positive")
	ErrPurchaseOrderLineDiscount         = errors.New("purchase order line discount must be between 0 and 100")
	ErrPurchaseOrderVendor               = errors.New("purchase order supplier does not exist")
	ErrPurchaseOrderVendorNotSupplier    = errors.New("purchase order supplier is not an active supplier")
	ErrPurchaseOrderWarehouse            = errors.New("purchase order warehouse does not exist")
	ErrPurchaseOrderVariant              = errors.New("purchase order item variant does not exist")
	ErrPurchaseOrderTax                  = errors.New("purchase order tax does not exist")
	ErrPurchaseOrderTaxInvalid           = errors.New("purchase order tax is not a purchase tax")
	ErrPurchaseOrderLocation             = errors.New("purchase order stock location not found")
	ErrPurchaseOrderSupplierLocation     = errors.New("no supplier stock location configured")
	ErrPurchaseOrderShipmentNotFound     = errors.New("purchase order incoming shipment not found")
	ErrPurchaseOrderNothingToReceive     = errors.New("purchase order has nothing ready to receive")
	ErrPurchaseOrderNothingToBill        = errors.New("purchase order has nothing ready to bill")
	ErrPurchaseOrderNoOpenBills          = errors.New("purchase order has no open supplier bills to pay")
	ErrPurchaseOrderApprovalRequired     = errors.New("purchase order requires an approved approval request")
	ErrPurchaseOrderApprovalPending      = errors.New("purchase order approval request is still pending")
	ErrPurchaseOrderApprovalThreshold    = errors.New("no approval threshold configured")
	ErrPurchaseOrderBillMismatch         = errors.New("supplier bill quantities exceed received or ordered quantities")
	ErrPurchaseOrderBillQualityBlocked   = errors.New("purchase order receipt has unresolved quality failures")
	ErrPurchaseOrderNoOffer              = errors.New("no supplier catalog price available for a purchase order line")
	ErrPurchaseOrderApprovalNotFound     = errors.New("purchase order approval request was refused")
	ErrPurchaseOrderNothingToReceiveDone = errors.New("purchase order already fully received")

	ErrRFQNotFound           = errors.New("purchase request for quotation not found")
	ErrQuoteRequestState     = errors.New("purchase request for quotation is not in the required state")
	ErrRFQNoLines            = errors.New("purchase request for quotation must have at least one line")
	ErrRFQLineQty            = errors.New("purchase request for quotation line quantity must be positive")
	ErrRFQRequester          = errors.New("purchase request for quotation requester does not exist")
	ErrRFQVendor             = errors.New("purchase request for quotation supplier does not exist")
	ErrRFQNotConvertible     = errors.New("purchase request for quotation must be sent before conversion")
	ErrRFQQuoteNotFound      = errors.New("purchase quotation not found")
	ErrSupplierQuoteState    = errors.New("purchase quotation is not in the required state")
	ErrRFQQuoteNoLines       = errors.New("purchase quotation must have at least one line")
	ErrRFQQuoteLineQty       = errors.New("purchase quotation line quantity must be positive")
	ErrRFQQuoteNoAccepted    = errors.New("no accepted purchase quotation available")
	ErrRFQQuoteVendor        = errors.New("purchase quotation supplier does not exist")
	ErrRFQQuoteNotSubmitted  = errors.New("purchase quotation must be submitted before it can be accepted")
	ErrRFQQuotePrice         = errors.New("purchase quotation line price cannot be negative")
	ErrRFQQuoteDuplicateLine = errors.New("purchase quotation references an unknown request line")

	ErrCurrencyRateNotFound = errors.New("currency exchange rate not found")
	ErrCurrencyRateInvalid  = errors.New("currency exchange rate is zero or invalid")
	ErrCurrencyRateExists   = errors.New("currency exchange rate already exists for this pair and date")

	ErrAgreementNotFound       = errors.New("purchase agreement not found")
	ErrSupplyAgreementState    = errors.New("purchase agreement is not in the required state")
	ErrAgreementNoLines        = errors.New("purchase agreement must have at least one line")
	ErrAgreementLineQty        = errors.New("purchase agreement line quantity must be positive")
	ErrAgreementVendor         = errors.New("purchase agreement supplier does not exist")
	ErrAgreementExpired        = errors.New("purchase agreement has expired")
	ErrAgreementQtyExceeded    = errors.New("purchase agreement quantity limit exceeded")
	ErrAgreementAmountExceeded = errors.New("purchase agreement amount limit exceeded")
	ErrAgreementNotActive      = errors.New("purchase agreement is not active")

	ErrScorecardNotFound = errors.New("supplier scorecard not found")

	ErrCostCenterNotFound = errors.New("cost center not found")
	ErrCostCenterInactive = errors.New("cost center is inactive")

	ErrCreditMemoNotFound = errors.New("purchase credit memo not found")
	ErrDebitMemoNotFound  = errors.New("purchase debit memo not found")

	ErrPaymentBatchNotFound          = errors.New("payment batch not found")
	ErrPaymentBatchNoOrders          = errors.New("payment batch must have at least one order")
	ErrPaymentBatchMixedVendors      = errors.New("payment batch orders must belong to the same supplier")
	ErrPaymentBatchInvalidOrderState = errors.New("payment batch order is not in a valid state")
	ErrPaymentBatchInvalidAmount     = errors.New("payment batch line amount must be positive")
	ErrPaymentBatchInvalidState      = errors.New("payment batch is not in a valid state")
)
