import camelcaseKeys from "camelcase-keys";
import snakecaseKeys from "snakecase-keys";

export function toSnakeCase(data: unknown): unknown {
  if (data === null || data === undefined || typeof data !== "object") {
    return data;
  }
  if (data instanceof FormData || data instanceof Blob) {
    return data;
  }
  return snakecaseKeys(data as Record<string, unknown> | readonly Record<string, unknown>[]);
}

export function toCamelCase(data: unknown): unknown {
  if (data === null || data === undefined || typeof data !== "object") {
    return data;
  }
  if (data instanceof Blob) {
    return data;
  }
  return camelcaseKeys(data, { deep: true });
}

const ACRONYMS = new Set([
  "crm",
  "pos",
  "hr",
  "planning",
  "recipe",
  "unit",
  "id",
  "sku",
  "po",
  "rma",
  "productionOrder",
]);

export function humanizeKey(value: string): string {
  const normalized = value.trim().toLowerCase().replace(/[_-]+/g, " ");
  const lookup = ID_LABELS[normalized];
  if (lookup) return lookup;
  const words = value
    .replace(/[_-]+/g, " ")
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .split(" ")
    .filter(Boolean);
  const joined = words.join(" ").toLowerCase();
  const phraseHit = ID_LABELS[joined];
  if (phraseHit) return phraseHit;
  return words
    .map((word) => {
      const lower = word.toLowerCase();
      if (ACRONYMS.has(lower)) return word.toUpperCase();
      const single = ID_LABELS[lower];
      if (single) return single;
      return word.charAt(0).toUpperCase() + word.slice(1);
    })
    .join(" ");
}

const ID_LABELS: Record<string, string> = {
  overview: "Ringkasan",
  modules: "Modul",
  settings: "Pengaturan",
  dashboard: "Dasbor",
  home: "Beranda",
  crm: "CRM",
  sales: "Penjualan",
  sale: "Penjualan",
  saleorders: "Pesanan Penjualan",
  "sale orders": "Pesanan Penjualan",
  "sale order": "Pesanan Penjualan",
  productionorders: "Perintah Produksi",
  "production orders": "Perintah Produksi",
  "production order": "Perintah Produksi",
  planning: "Perencanaan",
  purchases: "Pembelian",
  purchase: "Pembelian",
  "purchase orders": "Pesanan Pembelian",
  "purchase order": "Pesanan Pembelian",
  products: "Produk",
  product: "Produk",
  stock: "Stok",
  inventory: "Persediaan",
  employees: "Karyawan",
  employee: "Karyawan",
  leaverequests: "Pengajuan Cuti",
  "leave requests": "Pengajuan Cuti",
  "leave request": "Pengajuan Cuti",
  attendance: "Presensi",
  projects: "Proyek",
  project: "Proyek",
  payrollruns: "Penggajian",
  "payroll runs": "Penggajian",
  "payroll run": "Proses Gaji",
  payroll: "Penggajian",
  payslips: "Slip Gaji",
  payslip: "Slip Gaji",
  accounting: "Akuntansi",
  fixedassets: "Aset Tetap",
  "fixed assets": "Aset Tetap",
  "fixed asset": "Aset Tetap",
  quality: "Mutu",
  subscriptions: "Langganan",
  subscription: "Langganan",
  pos: "POS",
  expenses: "Biaya",
  expense: "Biaya",
  deferrals: "Penangguhan",
  deferral: "Penangguhan",
  service: "Layanan",
  commissions: "Komisi",
  commission: "Komisi",
  approvalrequests: "Permintaan Persetujuan",
  "approval requests": "Permintaan Persetujuan",
  "approval request": "Permintaan Persetujuan",
  activity: "Aktivitas",
  reference: "Referensi",
  reports: "Laporan",
  report: "Laporan",
  general: "Umum",
  organizations: "Organisasi",
  organization: "Organisasi",
  members: "Anggota",
  member: "Anggota",
  customers: "Pelanggan",
  customer: "Pelanggan",
  suppliers: "Pemasok",
  supplier: "Pemasok",
  contacts: "Kontak",
  contact: "Kontak",
  leads: "Prospek",
  lead: "Prospek",
  opportunities: "Peluang",
  opportunity: "Peluang",
  pipeline: "Pipa Penjualan",
  activities: "Aktivitas",
  tasks: "Tugas",
  task: "Tugas",
  milestone: "Tonggak",
  milestones: "Tonggak",
  name: "Nama",
  description: "Deskripsi",
  status: "Status",
  state: "Status",
  type: "Jenis",
  category: "Kategori",
  currency: "Mata Uang",
  amount: "Jumlah",
  total: "Total",
  subtotal: "Subtotal",
  date: "Tanggal",
  journal: "Jurnal",
  active: "Aktif",
  inactive: "Nonaktif",
  all: "Semua",
  view: "Lihat",
  edit: "Ubah",
  delete: "Hapus",
  save: "Simpan",
  cancel: "Batal",
  create: "Buat",
  add: "Tambah",
  search: "Cari",
  filter: "Filter",
  filters: "Filter",
  details: "Detail",
  summary: "Ringkasan",
  quantity: "Jumlah",
  qty: "Jml",
  price: "Harga",
  cost: "Biaya",
  revenue: "Pendapatan",
  profit: "Laba",
  loss: "Rugi",
  cash: "Kas",
  finance: "Keuangan",
  procurement: "Pengadaan",
  manufacturing: "Manufaktur",
  operations: "Operasional",
  warehouse: "Gudang",
  warehouses: "Gudang",
  location: "Lokasi",
  suppliercatalog: "Katalog Pemasok",
  "supplier catalog": "Katalog Pemasok",
  recipes: "Resep",
  pricebooks: "Daftar Harga",
  "price books": "Daftar Harga",
  timesheets: "Lembar Waktu",
  timesheet: "Lembar Waktu",
  departments: "Departemen",
  department: "Departemen",
  jobpositions: "Jabatan",
  "job positions": "Jabatan",
  "job position": "Jabatan",
  salaryrules: "Aturan Gaji",
  "salary rules": "Aturan Gaji",
  "salary rule": "Aturan Gaji",
  expensereports: "Laporan Biaya",
  returns: "Retur",
  return: "Retur",
  shipments: "Pengiriman",
  shipment: "Pengiriman",
  transfers: "Transfer",
  counts: "Opname",
  reorderrules: "Aturan Stok Ulang",
  contracts: "Kontrak",
  contract: "Kontrak",
  equipment: "Peralatan",
  plans: "Paket",
  plan: "Paket",
  orders: "Pesanan",
  order: "Pesanan",
  invoices: "Faktur",
  invoice: "Faktur",
  payments: "Pembayaran",
  payment: "Pembayaran",
  deliveries: "Pengiriman",
  giftcards: "Kartu Hadiah",
  sessions: "Sesi",
  session: "Sesi",
  register: "Kasir",
  checks: "Pemeriksaan",
  check: "Pemeriksaan",
  alerts: "Peringatan",
  alert: "Peringatan",
  points: "Titik",
  units: "Satuan",
  dimensions: "Dimensi",
  currencies: "Mata Uang",
  profile: "Profil",
  password: "Kata Sandi",
  email: "Email",
  phone: "Telepon",
  address: "Alamat",
  city: "Kota",
  country: "Negara",
  notes: "Catatan",
  note: "Catatan",
  priority: "Prioritas",
  stage: "Tahap",
  billing: "Penagihan",
  shipping: "Pengiriman",
  draft: "Draf",
  confirmed: "Dikonfirmasi",
  done: "Selesai",
  cancelled: "Dibatalkan",
  pending: "Menunggu",
  approved: "Disetujui",
  rejected: "Ditolak",
  paid: "Lunas",
  unpaid: "Belum Lunas",
  overdue: "Jatuh Tempo",
  open: "Terbuka",
  closed: "Ditutup",
  new: "Baru",
  qualified: "Berkualifikasi",
  won: "Menang",
  lost: "Kalah",
};
