package testutil

import (
	"strings"
	"testing"

	"gorm.io/gorm"
)

var cleanTables = []string{
	"user_email_verifications",
	"user_password_resets",
	"user_sessions",
	"users",
	"organizations",
	"members",
	"accounts",
	"journals",
	"taxes",
	"fx_rates",
	"tax_years",
	"tax_periods",
	"item_categories",
	"items",
	"item_variants",
	"price_books",
	"price_rules",
	"warehouses",
	"stock_locations",
	"shipments",
	"stock_movements",
	"stock_balances",
	"cost_layers",
	"stock_holds",
	"contacts",
	"contact_customers",
	"doc_sequences",
	"journal_entrys",
	"journal_lines",
	"account_partial_reconciles",
	"account_full_reconciles",
	"invoices",
	"invoice_lines",
	"invoice_taxes",
	"payments",
	"payment_allocations",
	"bank_statements",
	"bank_statement_lines",
	"fixed_assets",
	"asset_depreciation_lines",
	"pos_configs",
	"pos_sessions",
	"pos_orders",
	"pos_order_lines",
	"pos_payments",
	"subscription_plans",
	"subscriptions",
	"subscription_lines",
	"deferred_schedules",
	"deferred_schedule_lines",
	"expense_categories",
	"expense_reports",
	"expense_lines",
	"inbound_costs",
	"inbound_cost_lines",
	"inbound_cost_adjustments",
	"consumed_materials",
	"rma_lines",
	"commission_plans",
	"commission_rules",
	"commission_assignments",
	"commission_entries",
	"gift_cards",
	"gift_card_transactions",
	"equipments",
	"service_contracts",
	"service_orders",
	"service_order_lines",
	"dropship_links",
	"interorganization_rules",
	"interorganization_transactions",
	"consolidation_runs",
	"consolidation_eliminations",
	"departments",
	"job_positions",
	"salary_rules",
	"employees",
	"employment_contracts",
	"leave_types",
	"leave_requests",
	"attendances",
	"timesheets",
	"payroll_runs",
	"payslips",
	"payslip_lines",
	"job_runs",
	"integration_events",
	"webhook_deliveries",
	"webhook_subscriptions",
	"kpi_account_summaries",
	"attachments",
	"audit_logs",
}

func CleanTables(t *testing.T, database *gorm.DB) {
	t.Helper()

	statement := "TRUNCATE " + strings.Join(cleanTables, ", ") + " RESTART IDENTITY CASCADE"
	if err := database.Exec(statement).Error; err != nil {
		t.Fatalf("failed to clean tables: %v", err)
	}
}
